# @package _global_

# This is for when it is run on OCI with V100s (BM.GPU.A10.4)
defaults:
  - override /trainer: ddp.yaml

datamodule:
  batch_size: 16
  num_workers: 4

trainer:
  devices: 2
  num_nodes: 1
