# @package _global_

# This is for when it is run on OCI with A10s (BM.GPU.A10.4)
defaults:
  - override /trainer: ddp.yaml

datamodule:
  batch_size: 16
  num_workers: 64

trainer:
  devices: 4
  num_nodes: 1
