default_language_version:
  node: 20.8.0
  python: python3.11

# Only commit is installed by default: https://pre-commit.com/#pre-commit-install
# Pending rename of pre-push from: https://github.com/pre-commit/pre-commit/issues/2732
default_install_hook_types: ["commit-msg", "pre-commit"]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.10.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
        types: [text]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        types: [text]
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: debug-statements
        types: [python]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.27.0
    hooks:
      - id: check-github-workflows
        types: [yaml]

  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/hakancelik96/unimport
    rev: 1.0.0
    hooks:
      - id: unimport
        types: [python]
        args:
          - --ignore-init
          - --include-star-import
          - --gitignore

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.2
    hooks:
      - id: editorconfig-checker

  # - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks/
  #   rev: v2.10.0
  #   hooks:
  #     - id: pretty-format-toml
  #       types: [toml]
  #       args: [--autofix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [html, javascript, shell, yaml, json]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        types: [python]
        args: [--in-place, --wrap-summaries=99, --wrap-descriptions=99]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.292"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black-jupyter
        types: [python]
