_target_: cogelot.data.instance_transform.GobbledyGookPromptTokenTransform
timeout: 100
text_tokenizer:
  _target_: cogelot.modules.tokenizers.TextTokenizer
  pretrained_model: t5-base
  model_max_length: 512
