# @package _global_

defaults:
  - override /transformer_decoder@model.policy.transformer_decoder:
      - prompt_encoder_history_decoder.yaml
      - attn_layers/vima.yaml
      - attn_layers/with_cross_attn.yaml
      - positional/absolute.yaml
      - xattn_positional/absolute.yaml

architecture: encoder_decoder
attn_layers: vima
positional_encoding: absolute
xattn_positional_encoding: absolute
source: x-transformers
prompt_input: encoder
observation_input: decoder
num_action_tokens: 1
