defaults:
  - default.yaml
  - _self_

transformer_decoder:
  _target_: cogelot.nn.decoders.PolicyTransformerDecoder
  embed_dim: 768
  n_layers: 11

  transformer_decoder_layer:
    _target_: cogelot.nn.decoders.decoder_layers.VIMATransformerDecoderLayer
    embed_dim: 768
    sattn_n_heads: 24
    xattn_n_heads: 24
    dim_feedforward_multiplier: 4
    batch_first: True
    norm_first: True
