model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${output_dir}/checkpoints
  save_top_k: 2
  monitor: val_loss
  mode: min
  filename: "{epoch:02d}-{val_loss:.2f}"
