model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${output_dir}/checkpoints
  save_top_k: 4
  monitor: val_loss
  mode: min
  filename: "{epoch:02d}-{val_loss:.2f}"
