# @package _global_

defaults:
  - trainer: evaluation
  - /instance_preprocessor.yaml@model
  - evaluation_instance_transform@model.vima_instance_transform: none
  - model@model.model: from_their_policy
  - datamodule: evaluation
  - hydra: default
  - hardware: default
  - debug: null
  - _self_

task_name: "evaluate"

output_dir: ${hydra:runtime.output_dir}

# This is the seed they used in their example script
seed: 42

model:
  _target_: cogelot.models.EvaluationLightningModule

  environment:
    _target_: cogelot.environment.VIMAEnvironment.from_config
    seed: ${seed}
    # We're just giving it any task here, it will get changed during the steps
    task: 1
    partition: 1
    should_display_debug_window: false
    should_render_prompt: false
    should_hide_arm_rgb: true
    record_gui: false
