# @package _global_

defaults:
  - trainer: evaluation

  # Import the instance_preprocessor.yaml config into the model
  - /instance_preprocessor.yaml@model

  - datamodule: evaluation
  - hydra: default.yaml
  - hardware: default
  - debug: null
  - _self_

task_name: "evaluate"
output_dir: ${hydra:runtime.output_dir}

# This is the seed they used in their example script
seed: 42

wandb:
  entity: pyop
  project: CoGeLoT
  run_id: null

model:
  _target_: cogelot.models.EvaluationLightningModule

  model:
    _target_: cogelot.models.VIMALightningModule.from_wandb_run
    wandb_entity: ${trainer.logger.wandb.entity}
    wandb_project: ${trainer.logger.wandb.project}
    wandb_run_id: ${wandb.run_id}
    checkpoint_save_dir: "./storage/data/models"

  environment:
    _target_: cogelot.environment.VIMAEnvironment.from_config
    seed: ${seed}
    # We're just giving it any task here, it will get changed during the steps
    task: 1
    partition: 1
