# @package _global_

defaults:
  - trainer: evaluation
  - /instance_preprocessor.yaml@model
  - environment@model.environment: headless
  - evaluation_instance_transform@model.vima_instance_transform: noop
  - evaluation_prompt_modality@model: disable_none
  - model@model.model: from_hf_repo
  - datamodule: evaluation
  - hydra: default
  - hardware: default
  - debug: null
  - _self_

task_name: "evaluate"
output_dir: ${hydra:runtime.output_dir}
training_data: original

seed: 879008

model:
  _target_: cogelot.models.EvaluationLightningModule

  max_timesteps: 10
  should_stop_on_first_success: true
