defaults:
  - _self_

instance_preprocessor:
  _target_: cogelot.data.preprocess.InstancePreprocessor

  text_tokenizer:
    _target_: cogelot.modules.tokenizers.TextTokenizer
    pretrained_model: t5-base
    model_max_length: 512

  end_effector_tokenizer:
    _target_: cogelot.modules.tokenizers.EndEffectorTokenizer

  pose_action_tokenizer:
    _target_: cogelot.modules.tokenizers.PoseActionTokenizer
    n_discrete_x_bins: 50
    n_discrete_y_bins: 100
    n_discrete_z_bins: 50
    n_discrete_rotation_bins: 50
