# Running command
command:
  - ${env}
  - python
  - ${program}
  - train
  - ${args_no_hyphens}

program: src/cogelot/__main__.py

name: Overfit on a single example
entity: pyop
project: CoGeLoT

method: grid

parameters:
  experiment:
    values:
      - 00_overfit_single_example
      - 00_overfit_single_example_autoregressive

  datamodule.batch_size:
    values:
      - 1

  datamodule.task_index_seen:
    distribution: int_uniform
    max: 16
    min: 0

  datamodule.dataset_start_index:
    distribution: int_uniform
    max: 5
    min: 0
