# Running command
command:
  - ${env}
  - python
  - ${program}
  - hardware=eidf_4gpu
  - ${args_no_hyphens}

program: src/cogelot/entrypoints/train.py

name: 14tok again
entity: pyop
project: CoGeLoT

method: grid

parameters:
  experiment:
    values:
      # - 07_roformer_decoder_abs_1tok
      # - 01_their_vima
      - 01_their_vima_14tok
      # - 05_torch_vanilla_decoder_abs_14tok
      # - 06_t5_decoder_abs_14tok
      # - 02_vima_xattn_decoder_abs_1tok
      # - 02_vima_xattn_decoder_abs_14tok
      # - 03_vanilla_xattn_decoder_abs_1tok
      # - 03_vanilla_xattn_decoder_abs_14tok
      # - 04_no_xattn_decoder_abs_1tok
      # - 04_no_xattn_decoder_abs_14tok
      # - 02_vima_xattn_decoder_alibi_1tok
      # - 02_vima_xattn_decoder_alibi_14tok
      # - 03_vanilla_xattn_decoder_alibi_1tok
      # - 03_vanilla_xattn_decoder_alibi_14tok
      # - 04_no_xattn_decoder_alibi_1tok
      # - 04_no_xattn_decoder_alibi_14tok
      # - 02_vima_xattn_decoder_rope_1tok
      # - 02_vima_xattn_decoder_rope_14tok
      # - 03_vanilla_xattn_decoder_rope_1tok
      # - 03_vanilla_xattn_decoder_rope_14tok
      # - 04_no_xattn_decoder_rope_1tok
      # - 04_no_xattn_decoder_rope_14tok

  datamodule.dataset_variant:
    values:
      - original
      - reworded

  model.should_shuffle_obj_per_observations:
    values:
      - false
      - true
