# Running command
command:
  - ${env}
  - python
  - ${program}
  - hardware=eidf_4gpu
  - ${args_no_hyphens}

program: src/cogelot/entrypoints/train.py

name: Experiment 1
entity: pyop
project: CoGeLoT

method: grid

parameters:
  experiment:
    values:
      - 01_their_vima
      - 01_conceptual_vima

  datamodule.dataset_variant:
    values:
      - original
      - keep_null_action
