# Running command
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

program: src/cogelot/entrypoints/evaluate.py

name: Ablate Remaining

entity: pyop
project: cogelot-evaluation

method: grid

parameters:
  model.model.wandb_run_id:
    values:
      # Trained on original
      - 8lkml12g
      # Trained on reworded
      - 2df3mwfn

  evaluation_instance_transform:
    values:
      - textual
      - textual_gobbledygook_tokens
      - textual_gobbledygook_word
      - reworded

  # evaluation_prompt_modality:
  #   values:
  #     - disable_text
  #     - disable_visual
  #     - disable_both
