# @package _global_
hydra:
  job:
    env_set:
      NCCL_DEBUG: "INFO"
      NCCL_DEBUG_SUBSYS: ALL
      TORCH_CPP_LOG_LEVEL: INFO
      TORCH_DISTRIBUTED_DEBUG: INFO
      TORCH_SHOW_CPP_STACKTRACES: 1
