# @package _global_
defaults:
  - default.yaml
  - _self_

# Overfit the model to 3 batches
trainer:
  max_epochs: 50
  overfit_batches: 3

  enable_checkpointing: false

  # Also disable any checkpointing or early stopping
  callbacks:
    - _target_: lightning.pytorch.callbacks.RichModelSummary
      max_depth: -1
    - _target_: lightning.pytorch.callbacks.RichProgressBar
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: step
