# @package _global_

# Overfit the model to 3 batches

trainer:
  max_epochs: 50
  overfit_batches: 3

  # Also disable any checkpointing or early stopping
  callbacks:
    - _target_: lightning.pytorch.callbacks.RichModelSummary
      max_depth: -1
    - _target_: lightning.pytorch.callbacks.RichProgressBar
